before_install:
  - cd
  - wget http://download.osgeo.org/gdal/2.0.1/gdal-2.0.1.tar.gz
  - tar zxf gdal-2.0.1.tar.gz
  - cd gdal-2.0.1
  - ./configure
  - make
  - sudo make install
  - cd
  - wget http://download.osgeo.org/proj/proj-4.9.2.tar.gz
  - tar zxvf proj-4.9.2.tar.gz
  - cd proj-4.9.2
  - ./configure
  - make
  - sudo make install
  - cd /home/travis/build/edzer/trajectories
  - sudo R CMD javareconf  # for OpenStreetMaps

language: r
sudo: required

warnings_are_errors: true


